In [4]:
num=2
num1=3
num3=num+num1
print(num3)

a=10
b=2
c=a*(b)
c+=20

d=a>b

e= a<=b
print(c)
print(d)
print(e)

x=9
y=10
z=x/y
print(z)

y='x'
z='h'
v='k'
print(y)


name="mahesh"
type=" is a good boy"
print('{}+{} is {}'.format(name,type))



list1=[123,321,213,312,'mahesh','a']
print(2 in list1)
print(2 not in list1)
print(list1)
print(list1[1])

a='mahesh'
a.upper()


tuple1=(23,56,78,90,'a','b',[10,20])
print(tuple1)


p=90
q=91
r=q>p
print(r)


Q=-10
P=7
R=Q/P
print(R)
S=Q//P
print(S)

s="SIVA"
s.lower()

r="mAhEsH"
r.swapcase()

5
40
True
False
0.9
x

IndexError: ignored

In [ ]:
()